"""add itinerary versions

Revision ID: ba1f23606512
Revises: 0f1694ff8f8d
Create Date: 2026-09-11 14:17:44.241349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1f23606512'
down_revision: Union[str, Sequence[str], None] = '0f1694ff8f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('itinerary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_itinerary_versions_id'), 'itinerary_versions', ['id'], unique=False)
    op.drop_index(op.f('trips_ibfk_1'), table_name='trips')
    op.create_foreign_key(None, 'trips', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_index(op.f('trips_ibfk_1'), 'trips', ['user_id'], unique=False)
    op.drop_index(op.f('ix_itinerary_versions_id'), table_name='itinerary_versions')
    op.drop_table('itinerary_versions')
    # ### end Alembic commands ###
